Add unit tests
mingming-ma/txt2html pull request #16
Opened 2023-11-14 18:50 UTC by avelynhc

- added unit tests for method, `process_text_file` and `contains_italics`
- change from `exit()` to `raise` when handling file not found error in `txt2html.py`
- change `.` location before proceed to add more unit tests in `tests/test_process_line.py`

result
<img width="1643" alt="Screenshot 2023-11-14 at 1 44 54 PM" src="https://github.com/mingming-ma/txt2html/assets/75185537/6d6579b7-27be-4a18-88ac-9555ce8f20dd">

2023-11-16 00:17 UTC, mingming-ma commented
@avelynhc Hi, thanks a lot for your contribution, it seems you use another framework which is supported by Pytest, if you have time can you convert them to Pytest style? 🙏

2023-11-16 00:32 UTC, avelynhc commented
@mingming-ma is this better? let me know. Thanks!

<img width="982" alt="Screenshot 2023-11-15 at 7 31 45 PM" src="https://github.com/mingming-ma/txt2html/assets/75185537/4ddb90c9-7744-4938-8c5d-f77241787d14">

2023-11-17 01:30 UTC, mingming-ma requested changes

2023-11-17 01:30 UTC, mingming-ma commented on tests/test_process_line.py
> +        ("This should be *italic.*", "This should be <i>italic.</i>"),
Bug fixed, no needed here

2023-11-17 01:30 UTC, mingming-ma commented on tests/test_process_line.py
> +    @patch("builtins.print")
seems indent should also update after the change, and following cases also

2023-11-17 01:58 UTC, avelynhc commented
@mingming-ma I just made some changes as per your request. Please let me know if you need anything else. Thanks!

2023-11-17 02:53 UTC, mingming-ma commented
@avelynhc Thanks for your PR

2023-11-17 02:53 UTC, merged